[package]
name = "porcelain"
version = "0.1.0"
authors = ["Chris Zehner <chris@cbzehner.com>"]
edition = "2018"

[dependencies]
yaml-rust = "0.4.5"

[dependencies.clap]
git = "https://github.com/cbzehner/clap"
branch = "ignore-extra-fields-on-arg"
features = ["yaml"]