[package]
name = "porcelain"
version = "0.1.0"
authors = ["Chris Zehner <chris@cbzehner.com>"]
edition = "2018"

[dependencies]
atty = "0.2"
yaml-rust = "0.4.5"

[dependencies.clap]
git = "https://github.com/clap-rs/clap"
features = ["yaml"]