[package]
name = "porcelain"
version = "0.1.0"
authors = ["Chris Zehner <chris@cbzehner.com>"]
edition = "2018"

[dependencies]
yaml-rust = "0.3.5"

[dependencies.clap]
version = "2"
features = ["yaml"]